const selectors = {
  main: document.querySelector('main'),
  form: document.querySelector('#formContainer'),
  player0El: document.querySelector('.player--0'),
  player1El: document.querySelector('.player--1'),
  score0El: document.querySelector('#score--0'),
  score1El: document.getElementById('score--1'),
  current0El: document.getElementById('current--0'),
  current1El: document.getElementById('current--1'),
  diceEl: document.querySelector('.dice'),
  btnNew: document.querySelector('.btn--new'),
  btnRoll: document.querySelector('.btn--roll'),
  btnHold: document.querySelector('.btn--hold'),
  winner: document.querySelector('.player--wins'),
  gameOver: document.querySelector('.game-over'),
  compututerWins: document.querySelector('.computerWins'),
  winnerSound: document.querySelector('.winner-sound'),
  diceSound: document.querySelector('.dice-sound'),
  user0El: document.getElementById('name--0'),
  user1El: document.getElementById('name--1'),
  firstUserInput: document.getElementById('user1'),
  secondUserInput: document.getElementById('user2'),
  startButton: document.querySelector('.startBtn'),
  gameOverSound: document.querySelector('.gameOver'),
  holdSound: document.querySelector('.hold-sound'),
  winnerDisplay: document.querySelector('.player--wins'),
  user1ScoreDisplay: document.querySelector('.user1ScoreDisplay'),
  user2ScoreDisplay: document.querySelector('.user2ScoreDisplay'),
  startPlayingHeader: document.querySelector('.sp'),
  warning: document.querySelector('.warning'),
  timer: document.querySelector('.timer'),
  resetScore: document.querySelector('.resetScore'),
  darkMood: document.querySelector('.dk-container'),
};
export default selectors;